#!/bin/sh

while true
do
    cat /sys/devices/system/cpu/online
    cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_cur_freq /sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_cur_freq /sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_cur_freq
    sleep 1
done
